/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PurgedButton {
    }
    interface UnpurgedButton {
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPurgedButtonElement extends Components.PurgedButton, HTMLStencilElement {
    }
    var HTMLPurgedButtonElement: {
        prototype: HTMLPurgedButtonElement;
        new (): HTMLPurgedButtonElement;
    };
    interface HTMLUnpurgedButtonElement extends Components.UnpurgedButton, HTMLStencilElement {
    }
    var HTMLUnpurgedButtonElement: {
        prototype: HTMLUnpurgedButtonElement;
        new (): HTMLUnpurgedButtonElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "purged-button": HTMLPurgedButtonElement;
        "unpurged-button": HTMLUnpurgedButtonElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PurgedButton {
    }
    interface UnpurgedButton {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "purged-button": PurgedButton;
        "unpurged-button": UnpurgedButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "purged-button": LocalJSX.PurgedButton & JSXBase.HTMLAttributes<HTMLPurgedButtonElement>;
            "unpurged-button": LocalJSX.UnpurgedButton & JSXBase.HTMLAttributes<HTMLUnpurgedButtonElement>;
        }
    }
}
